name: age-encryption
base: core24
adopt-info: age
summary: Simple, modern and secure file encryption tool
description: |
  A simple, modern and secure encryption tool (and Go library) with small
  explicit keys, no config options, and UNIX-style composability.

title: age
license: BSD-3-Clause
website: https://github.com/FiloSottile/age
source-code: https://github.com/nooreldeensalah/age-snap
issues: https://github.com/nooreldeensalah/age-snap/issues
contact: https://github.com/nooreldeensalah/age-snap/issues

grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:
  arm64:

apps:
  age:
    command: bin/age
    plugs: [home, removable-media]
    aliases: [age]

  age-keygen:
    command: bin/age-keygen
    plugs: [home, removable-media]
    aliases: [age-keygen]

  age-inspect:
    command: bin/age-inspect
    plugs: [home, removable-media]
    aliases: [age-inspect]


parts:
  age:
    plugin: go
    source: https://github.com/FiloSottile/age.git
    source-tag: v1.3.1
    source-depth: 1

    build-snaps:
      - go/latest/stable

    build-environment:
      - CGO_ENABLED: "0"

    go-buildtags: [netgo, osusergo]

    override-build: |
      craftctl default
      craftctl set version="$(git describe --tags --always | sed 's/^v//')"
